Issue 28 feat/api user service
coders-camp-2021-best-team/TeamUp-API pull request #39
Opened 2022-03-03 17:48 UTC by Mariusz-web

2022-03-05 21:50 UTC, Veryyapeee commented on src/user/user.controller.ts
> +        const userToUpdate = body;
what for is this constant? just put the body in `UserService.updateUser`

2022-03-05 21:50 UTC, Veryyapeee commented on src/user/user.service.ts
> +        if (!user) return null;
use `if(){}` syntax

2022-03-05 21:50 UTC, Veryyapeee commented on src/user/user.service.ts
> +        if (!user) return null;
same here about the syntax

2022-03-06 13:00 UTC, PoProstuMieciek requested changes

2022-03-06 13:00 UTC, PoProstuMieciek commented on yarn.lock
Don't use NPM! Please, revert changes to this file.

2022-03-06 14:48 UTC, PoProstuMieciek approved these changes

2022-03-06 14:51 UTC, Veryyapeee approved these changes

2022-03-06 15:16 UTC, merged