Issue 52 feat/api create game service
coders-camp-2021-best-team/TeamUp-API pull request #58
Opened 2022-03-10 19:57 UTC by KonTra7cf

2022-03-17 19:45 UTC, Veryyapeee approved these changes

2022-03-17 19:57 UTC, PoProstuMieciek requested changes

2022-03-17 19:57 UTC, PoProstuMieciek commented on src/common/middlewares/game.middleware.ts
> +export const gameMiddleware: Middleware = async (req, res, next) => {
Why using middleware? It just doesn't seem right really. @Veryyapeee let me know if this is needed. I think the cleaner solution would be checking it in request.

2022-03-17 19:59 UTC, PoProstuMieciek requested changes

2022-03-17 19:59 UTC, PoProstuMieciek commented on src/index.ts
> +    middlewares: [funnyHeaderMiddleware, gameMiddleware],
We don't want to use this middleware globally. It will probably break other endpoints.

2022-03-18 15:25 UTC, PoProstuMieciek requested changes
everything is almost perfect

**quick summary:**
one endpoint (for listing game levels) is missing
try catch blocks are not required
we don't need to send additional text to report errors. http codes are enough
HTTP NO_CONTENT is not perfect in this case. just use HTTP OK

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +        router.delete('/:id/experience/:lvl_id', this.removeExperienceLevel);
maybe do `/:id/level/:lvl_id`

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +        try {
remove the try catch block
no need to catch errors here
i already did this globally

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +        try {
remove try catch

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +                return res.status(StatusCodes.NOT_FOUND).send('Game not found');
also please remove the text from .send()
`Game not found` is not needed. we have a status code that tells us the same

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +                return res.status(StatusCodes.NOT_FOUND).send('Game not found');
remove `Game not found`

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +                .send('Game has been removed');
NO_CONTENT 204 should be just OK 200
also `Game has been removed` is not essential. we have status code

change that to `return res.send();`

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +        try {
remove try catch

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +                return res.status(StatusCodes.NOT_FOUND).send('Game not found');
~~Game not found~~

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +        try {
rmeov try catch

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +                return res.status(StatusCodes.NOT_FOUND).send('Game not found');
~~Game not found~~

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +                    .send('Experience level not found');
~~Experience level not found~~

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +                .send('Experience level has been removed');
~~NO_CONTENT~~ **OK**
~~Experience level has been removed~~
**`return res.send();`**

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.service.ts
> +        if (!games.length) {
`if` not needed
we will always get an array or an empty array

2022-03-18 15:25 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +        router.post('/:id/experience', this.addExperienceLevel);
`router.get('/:id/experience', this.getExperienceLevels);`
one endpoint is missing

2022-03-18 19:44 UTC, PoProstuMieciek requested changes

2022-03-18 19:44 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +        return res.send(await GameService.getExperienceLevels());
you need to get levels of the specified game

now you are printing every level despite being given a game
you need to somewhat pass the game into GameService.getExperienceLevels()

2022-03-19 21:58 UTC, PoProstuMieciek approved these changes
if it works, then lets merge

2022-03-19 21:58 UTC, PoProstuMieciek commented on src/game/game.service.ts
> +                id: `${gameId}`
id: gameId

2022-03-19 22:01 UTC, PoProstuMieciek requested changes

2022-03-19 22:01 UTC, PoProstuMieciek commented on src/game/game.controller.ts
> +        }
remove useless lines 68-74:
```ts
const game = await GameService.getGame(game_id);

        if (!game) {
            return res
                .status(StatusCodes.NOT_FOUND)
                .send(ReasonPhrases.NOT_FOUND);
        }
```

2022-03-20 19:59 UTC, PoProstuMieciek approved these changes

2022-03-20 19:59 UTC, merged